export enum TestId {
  CardItem = 'card-item',
  CardName = 'card-name',
  CardEmail = 'card-email',
  CardPhone = 'card-phone',
  CardList = 'card-list',
  SearchField = 'search-field',
  Footer = 'footer',
  FooterLink = 'footer-link',
  Header = 'header',
  HeaderTitle = 'header-title',
  HomePageLink = 'home-page-link',
  AboutPageLink = 'about-page-link',
  Layout = 'layout',
  Main = 'main',
  ImageAbout = 'image-about',
  TextAbout = 'text-about',
}
